# Generated by Django 6.0.2 on 2026-03-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('admin', 'Admin'), ('manager', 'Manager')], default='worker', max_length=50),
        ),
    ]
