# Generated by Django 6.0.2 on 2026-03-26 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('preferred_attendant_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_worker', models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_bookings', to='workshop.user')),
                ('preferred_attendant', models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='workshop.user')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='workshop.service')),
            ],
        ),
    ]
